raw_data_path = '../data/raw/infreemation/'
processed_data_path = '../data/processed/'
nltk_data_path_local = "../data/external/nltk_data/"
nltk_data_path_container = "/app/data/external/nltk_data/"
model_path = '../models/'
lookups_path = '../data/processed/search-lookups/'
viz_path = '../data/processed/dashboard/'
preprocessed_filename = 'infreemation-preprocessed.pickle'
tokenized_filename = '02-tokenized-without-run-togethers.pickle'
tfidf_filename = '02-tfidf-without-run-togethers.model'
search_lookup_filename = '03-df-lookup-subjects-requestbodies-tfidf.pickle'
word_model_filename = '03-word2vec-subjects-requestbodies-without-run-togethers.model'
viz_df_filename = '03-df-viz.pickle'
preprocessed_filepath = processed_data_path + preprocessed_filename
word_model_filepath = model_path + word_model_filename
search_lookup_filepath = lookups_path + search_lookup_filename
viz_df_filepath = viz_path + viz_df_filename
tokenized_filepath = model_path + tokenized_filename
tfidf_filepath = model_path + tfidf_filename
